CREATE TABLE tax_regimes (
     id SERIAL PRIMARY KEY,
     code INTEGER UNIQUE NOT NULL,
     description VARCHAR(200) NOT NULL,
     is_active BOOLEAN DEFAULT true,
     created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     deleted_date TIMESTAMP
);

INSERT INTO tax_regimes (code, description, is_active) VALUES
       (601, 'REGIMEN GENERAL DE LEY PERSONAS MORALES', true),
       (602, 'RÉGIMEN SIMPLIFICADO DE LEY PERSONAS MORALES', true),
       (603, 'PERSONAS MORALES CON FINES NO LUCRATIVOS', true),
       (604, 'RÉGIMEN DE PEQUEÑOS CONTRIBUYENTES', true),
       (605, 'RÉGIMEN DE SUELDOS Y SALARIOS E INGRESOS ASIMILADOS A SALARIOS', true),
       (606, 'RÉGIMEN DE ARRENDAMIENTO', true),
       (607, 'RÉGIMEN DE ENAJENACIÓN OR ADQUISICIÓN DE BIENES', true),
       (608, 'RÉGIMEN DE LOS DEMÁS INGRESOS', true),
       (609, 'RÉGIMEN DE CONSOLIDACIÓN', true),
       (610, 'RÉGIMEN RESIDENTES EN EL EXTRANJERO SIN ESTABLECIMIENTO PERMANENTE EN MÉXICO', true),
       (611, 'RÉGIMEN DE INGRESOS POR DIVIDENDOS (SOCIOS Y ACCIONISTAS)', true),
       (612, 'RÉGIMEN DE LAS PERSONAS FÍSICAS CON ACTIVIDADES EMPRESARIALES Y PROFESIONALES', true),
       (613, 'RÉGIMEN INTERMEDIO DE LAS PERSONAS FÍSICAS CON ACTIVIDADES EMPRESARIALES', true),
       (614, 'RÉGIMEN DE LOS INGRESOS POR INTERESES', true),
       (615, 'RÉGIMEN DE LOS INGRESOS POR OBTENCIÓN DE PREMIOS', true),
       (616, 'SIN OBLIGACIONES FISCALES', true),
       (617, 'PEMEX', true),
       (618, 'RÉGIMEN SIMPLIFICADO DE LEY PERSONAS FÍSICAS', true),
       (619, 'INGRESOS POR LA OBTENCIÓN DE PRÉSTAMOS', true),
       (620, 'SOCIEDADES COOPERATIVAS DE PRODUCCIÓN QUE OPTAN POR DIFERIR SUS INGRESOS.', true),
       (621, 'RÉGIMEN DE INCORPORACIÓN FISCAL', true),
       (622, 'RÉGIMEN DE ACTIVIDADES AGRÍCOLAS, GANADERAS, SILVÍCOLAS Y PESQUERAS PM', true),
       (623, 'RÉGIMEN DE OPCIONAL PARA GRUPOS DE SOCIEDADES', true),
       (624, 'RÉGIMEN DE LOS COORDINADOS', true),
       (625, 'RÉGIMEN DE LAS ACTIVIDADES EMPRESARIALES CON INGRESOS A TRAVÉS DE PLATAFORMAS TECNOLÓGICAS.', true),
       (626, 'RÉGIMEN SIMPLIFICADO DE CONFIANZA', true)
    ON CONFLICT (code) DO UPDATE SET
    description = EXCLUDED.description,
    updated_date = CURRENT_TIMESTAMP;